server:
  port: 8081
  servlet:
    session:
      cookie:
        secure: false     # для HTTPS поставить true
        http-only: true # Защита от JavaScript-доступа
        same-site: none # Убедитесь, что cookie передаются для редиректов
      tracking-modes: cookie

spring:
  application:
    name: AuthService
  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: a0bc7b7381a84739be01111f12d9447e
            client-secret: c0701b6fad07403c8a8b6f9e99874e1f
            scope:
              - login
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/yandex"  # "{baseUrl}/login/oauth2/code/yandex"
            client-name: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: id
    password:
      encoder-strength: 12

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

jwt:
  secret: e0ccMN3fqRE30HcE6Me2xnGF88e1xVrGwNndNzTd
  expiration:
    access: 3600000  # 1 ???
    refresh: 86400000  # 1 ????

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG