spring:
  datasource:
    url: jdbc:postgresql://<POSTGRES_HOST>:5432/authdb
    username: <POSTGRES_USER>
    password: <POSTGRES_PASSWORD>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: your-super-secret-key
  expiration:
    access: 3600000  # 1 час
    refresh: 86400000  # 1 день

server:
  port: 8081
