server:
  port: 8081

spring:
  application:
    name: AuthService

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: authuser
    password: authpassword
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

jwt:
  secret: my-super-secret-key
  expiration:
    access: 3600000  # 1 ???
    refresh: 86400000  # 1 ????

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
